const news=require('../data/news.json');
const covers={
 'thien-phuc-vinh-hang-vien-uong-bi-yen-tu':'/assets/uploads/overview-1787919202977.jpg',
 'kinh-nghiem-lua-chon-cong-vien-nghia-trang':'/assets/uploads/location-1787918305654.jpg',
 'mo-don-mo-doi-khu-gia-toc-khac-nhau-the-nao':'/assets/uploads/productDouble-1787918413234.jpg',
 'y-nghia-canh-quan-xanh-trong-hoa-vien-nghia-trang':'/assets/uploads/amenityGarden-1787918481252.jpg',
 'tham-quan-thien-phuc-vinh-hang-vien-can-tim-hieu-gi':'/assets/uploads/amenityOffice-1787918498872.jpg',
 'cham-soc-mo-phan-lau-dai':'/assets/uploads/amenityCare-1787918529370.jpg'
};
const extra={
 'thien-phuc-vinh-hang-vien-uong-bi-yen-tu':['/assets/uploads/location-1787918305654.jpg','/assets/uploads/amenityGarden-1787918481252.jpg'],
 'kinh-nghiem-lua-chon-cong-vien-nghia-trang':['/assets/uploads/overview-1787919202977.jpg','/assets/uploads/amenityGarden-1787918481252.jpg'],
 'mo-don-mo-doi-khu-gia-toc-khac-nhau-the-nao':['/assets/uploads/productSingle-1787918273700.jpg','/assets/uploads/productFamily-1787918353180.jpg'],
 'y-nghia-canh-quan-xanh-trong-hoa-vien-nghia-trang':['/assets/uploads/overview-1787919202977.jpg','/assets/uploads/amenityLake-1787918458877.jpg'],
 'tham-quan-thien-phuc-vinh-hang-vien-can-tim-hieu-gi':['/assets/uploads/location-1787918305654.jpg','/assets/uploads/overview-1787919202977.jpg'],
 'cham-soc-mo-phan-lau-dai':['/assets/uploads/amenityGarden-1787918481252.jpg','/assets/uploads/overview-1787919202977.jpg']
};
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
module.exports=(req,res)=>{
 const id=String(req.query.id||''); const n=(news.items||[]).find(x=>x.id===id&&x.status==='published');
 if(!n){res.statusCode=404;res.setHeader('X-Robots-Tag','noindex, follow');return res.end('<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="robots" content="noindex,follow"><title>Không tìm thấy bài viết</title></head><body><h1>Không tìm thấy bài viết</h1><a href="/tin-tuc.html">Xem tin tức</a></body></html>')}
 const origin='https://www.thienphucvinhhangvien.net'; const url=origin+'/tin-tuc/'+encodeURIComponent(n.id)+'.html'; const cover=covers[n.id]||'/assets/uploads/overview-1787919202977.jpg'; const image=origin+cover; const desc=String(n.excerpt||n.content||'').replace(/\s+/g,' ').slice(0,160); const ex=extra[n.id]||['/assets/uploads/overview-1787919202977.jpg','/assets/uploads/amenityGarden-1787918481252.jpg'];
 const blocks=String(n.content||'').split(/\n+/).filter(Boolean); let body=''; blocks.forEach((p,i)=>{const heading=/^(\d+\.|Không gian|Vị trí|Các loại|Hệ thống|Lựa chọn|Mộ đơn|Mộ đôi|Khu gia tộc|Nên lựa chọn)/i.test(p);body+=(heading?'<h2>':'<p>')+esc(p)+(heading?'</h2>':'</p>');if(i===2)body+='<figure class="wide-image"><img src="'+ex[0]+'" alt="Không gian Thiên Phúc Vĩnh Hằng Viên liên quan đến '+esc(n.title)+'" loading="lazy"></figure>';if(i===5)body+='<figure class="wide-image"><img src="'+ex[1]+'" alt="Cảnh quan dự án Thiên Phúc Vĩnh Hằng Viên" loading="lazy"></figure>'});
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:n.title,description:desc,image:[image,origin+ex[0],origin+ex[1]],datePublished:n.publishedAt,dateModified:n.updatedAt||n.publishedAt,mainEntityOfPage:url,inLanguage:'vi-VN',author:{'@type':'Organization',name:'Thiên Phúc Vĩnh Hằng Viên'},publisher:{'@type':'Organization',name:'Thiên Phúc Vĩnh Hằng Viên',url:origin+'/'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Trang chủ',item:origin+'/'},{'@type':'ListItem',position:2,name:'Tin tức',item:origin+'/tin-tuc.html'},{'@type':'ListItem',position:3,name:n.title,item:url}]}]};
 const html='<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(n.title)+' | Thiên Phúc Vĩnh Hằng Viên</title><meta name="description" content="'+esc(desc)+'"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="'+url+'"><meta property="og:locale" content="vi_VN"><meta property="og:type" content="article"><meta property="og:site_name" content="Thiên Phúc Vĩnh Hằng Viên"><meta property="og:title" content="'+esc(n.title)+'"><meta property="og:description" content="'+esc(desc)+'"><meta property="og:url" content="'+url+'"><meta property="og:image" content="'+image+'"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">'+json(schema)+'</script><link rel="stylesheet" href="/styles.css"></head><body><header class="site-header"><div class="wrap nav"><a class="brand" href="/index.html"><img src="/assets/uploads/overview-1787919202977.jpg" alt="Thiên Phúc Vĩnh Hằng Viên"></a><button class="menu-toggle" aria-label="Mở menu">☰</button><nav class="main-nav"><a href="/index.html">Trang chủ</a><a href="/gioi-thieu.html">Giới thiệu</a><a href="/san-pham.html">Sản phẩm</a><a href="/vi-tri.html">Vị trí</a><a href="/tien-ich.html">Tiện ích</a><a href="/phoi-canh.html">Phối cảnh</a><a href="/tin-tuc.html">Tin tức</a><a href="/lien-he.html">Liên hệ</a></nav><a class="nav-cta" href="/lien-he.html">Đăng ký tham quan</a></div></header><main><section class="article-hero"><div class="wrap"><a class="back" href="/tin-tuc.html">← Tin tức Thiên Phúc</a><h1>'+esc(n.title)+'</h1><p>'+esc(String(n.publishedAt||'').split('-').reverse().join('.'))+'</p></div></section><article class="wrap article"><img class="article-cover" src="'+cover+'" alt="Ảnh đại diện '+esc(n.title)+'" loading="eager"><p class="lead">'+esc(n.excerpt||'')+'</p>'+body+(n.source?'<div class="source-box"><b>Nguồn:</b> '+esc(n.source)+'</div>':'')+'<p><a class="text-link" href="/gioi-thieu.html">Tìm hiểu Thiên Phúc Vĩnh Hằng Viên</a> · <a class="text-link" href="/lien-he.html">Đăng ký tham quan dự án</a></p></article></main><footer class="site-footer"><div class="wrap footer-grid"><div><strong>Thiên Phúc Vĩnh Hằng Viên</strong><p>Hoa viên nghĩa trang sinh thái tại Uông Bí – Yên Tử, Quảng Ninh.</p></div><div><strong>Khám phá</strong><a href="/gioi-thieu.html">Giới thiệu</a><a href="/san-pham.html">Sản phẩm</a><a href="/tien-ich.html">Tiện ích</a></div><div><strong>Thông tin</strong><a href="/tin-tuc.html">Tin tức</a><a href="/lien-he.html">Liên hệ</a></div></div></footer><script src="/script.js"></script></body></html>';
 res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Robots-Tag','index, follow, max-image-preview:large');res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=86400');res.end(html);
};